### ISSUE TITLE
Connection port

### ISSUE THREAD

**Issue by angleman** [kessler/redshift-cli#4]
Is there a way to set the connection port?

AWS appears to be setting the port to 5439; however, redshift-cli is attempt to access via port 5432. This is true even if the config.json connectionString ends in :5439

Thoughts?

**Comment by haoduotnt** [comment]
`{
	"connectionString": "tcp://test:K&4#123@endpointother.redshift.amazonaws.com:5439/",
	"database": "ecpm",
	"accessKeyId": "test", 
	"secretAccessKey": "s",	
	"region": "[amazon region]",
	"defaultS3BucketName": "[some bucket used for load and unload operations - this can be specified later]"
	"sslEnabled": true,
	"gzip": true,
	"delimiter": "|"
}`

[something].redshift.amazonaws.com:5439 : this set the redshift endpoint?
the same error:redshift-cli is attempt to access via port 5432

debugger:pg/lib/connection-parameters.js lines 50
console config:
port: null,
  host: 'test',
  database: ':K&4',
  user: '',
  password: ''

**Comment by kessler** [comment]
Maybe your rc config is not being read properly?

Can you try with the command line params as I asked a few years ago? :-)

**Comment by haoduotnt** [comment]
the error is because redshift password contain some special characters. I appreciate your rapid reply.

**Comment by kessler** [comment]
You're welcome
